language: python
python:
  - 3.6

before_install: 
  - pip3 install numpy
  - curl -L http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz --output ta-lib-0.4.0-src.tar.gz
  - tar zxf ta-lib-0.4.0-src.tar.gz
  - cd ta-lib && ./configure --prefix=/usr && make && sudo make install && cd ..

install: 
  - pip3 install -r requirements.txt
  - pip3 install TA-Lib
  - pip3 install nose

script:
  - nosetests tests/data.py
  - nosetests tests/engine.py
  - nosetests tests/exchange.py
  - nosetests tests/helpers.py